### ISSUE TITLE
Discussion about 0.1.0.

### ISSUE THREAD

**Issue by sainthkh** [sainthkh/reason-relay#1]
# Things to do for 0.1.0

The goal of 0.1.0 is to create the minimal tool set. (In other words, we need features to port [todomvc example](https://github.com/relayjs/relay-examples).)

## Todo

- [x] Reason type generation: basics - nullable/non-nullable scalar, object, array.
- [ ] Purge functions - remove unnecessary members in records. 
- [x] Rewrite relay-compiler-language-reasonml in JavaScript. 
- [ ] Generate data type files at TagFinder
- [x] MakeQueryRenderer functor.
- [ ] Support fragment container. 
- [ ] Mutation
- [ ] documentation website: Installation 

## Examples to make
- [ ] hello graphql world - execute simple GraphQL query. 
- [ ] mini twitter - only has the feature of adding new message. 
- [ ] todomvc -
